const products = [
    // Shrimp
    {
        id: 1,
        title: '6 Shrimp',
        price: 7.19,
        group: 'Shrimp',
        amount: 1,
    },
    {
        id: 2,
        title: '9 Shrimp',
        price: 9.19,
        group: 'Shrimp',
        amount: 1,
    },
    {
        id: 3,
        title: '12 Shrimp',
        price: 10.89,
        group: 'Shrimp',
        amount: 1,
    },
    // Fish
    {
        id: 4,
        title: '2 Fish',
        price: 7.29,
        group: 'Fish',
        amount: 1,
    },
    {
        id: 5,
        title: '3 Fish',
        price: 9.29,
        group: 'Fish',
        amount: 1,
    },
    {
        id: 6,
        title: '4 Fish',
        price: 11.29,
        group: 'Fish',
        amount: 1,
    },
    // Oysters
    {
        id: 7,
        title: '6 Oysters',
        price: 8.79,
        group: 'Oysters',
        amount: 1,
    },
    {
        id: 8,
        title: '9 Oysters',
        price: 11.29,
        group: 'Oysters',
        amount: 1,
    },
    {
        id: 9,
        title: '12 Oysters',
        price: 14.29,
        group: 'Oysters',
        amount: 1,
    },
    // Fish Strips
    {
        id: 10,
        title: '6 Fish Strips (Fries Only)',
        price: 5.79,
        group: 'Fish',
        amount: 1,
    },
    {
        id: 11,
        title: '9 Fish Strips (Fries Only)',
        price: 6.79,
        group: 'Fish',
        amount: 1,
    },
    {
        id: 12,
        title: '12 Fish Strips (Fries Only)',
        price: 7.79,
        group: 'Fish',
        amount: 1,
    },
    {
        id: 13,
        title: '12 Fish Strips Only',
        price: 6.99,
        group: 'Fish',
        amount: 1,
    },
    {
        id: 14,
        title: 'Popcorn Fish (Fries Only)',
        price: 6.39,
        group: 'Fish',
        amount: 1,
    },
    // Combination Order
    {
        id: 15,
        title: '6 Shrimp & 1 Fish',
        price: 9.29,
        group: 'Combination Order',
        amount: 1,
    },
    {
        id: 16,
        title: '6 Shrimp & 2 Fish',
        price: 11.29,
        group: 'Combination Order',
        amount: 1,
    },
    {
        id: 17,
        title: '3 Shrimp & 3 Oysters',
        price: 7.79,
        group: 'Combination Order',
        amount: 1,
    },
    {
        id: 18,
        title: '6 Oysters & 1 Fish',
        price: 10.99,
        group: 'Combination Order',
        amount: 1,
    },
    {
        id: 19,
        title: '3 Shrimp 3 Oyster 1 Fish',
        price: 9.79,
        group: 'Combination Order',
        amount: 1,
    },
    {
        id: 20,
        title: '6 Shrimp 3 Oyster 2 Fish',
        price: 14.89,
        group: 'Combination Order',
        amount: 1,
    },
    {
        id: 21,
        title: '3 Shrimp 6 Oyster 2 Fish',
        price: 16.09,
        group: 'Combination Order',
        amount: 1,
    },
    {
        id: 22,
        title: '3 Shrimp 3 Oyster 1 Fish 1 Egg Roll (Rice)',
        price: 11.89,
        group: 'Combination Order',
        amount: 1,
    },
    // Popcorn Shrimp
    {
        id: 23,
        title: 'Popcorn Shrimp',
        price: 7.19,
        group: 'Popcorn Shrimp',
        amount: 1,
    },
    {
        id: 24,
        title: 'Popcorn Shrimp & 1 Fish',
        price: 9.19,
        group: 'Popcorn Shrimp',
        amount: 1,
    },
    {
        id: 25,
        title: 'Popcorn Shrimp & 4 Strips',
        price: 9.19,
        group: 'Popcorn Shrimp',
        amount: 1,
    },
    {
        id: 26,
        title: 'Popcorn Shrimp & 2 Fish',
        price: 11.19,
        group: 'Popcorn Shrimp',
        amount: 1,
    },
    {
        id: 27,
        title: 'Small Popcorn Shrimp Only',
        price: 6.69,
        group: 'Popcorn Shrimp',
        amount: 1,
    },
    {
        id: 28,
        title: 'Large Popcorn Shrimp',
        price: 11.19,
        group: 'Popcorn Shrimp',
        amount: 1,
    },
    {
        id: 29,
        title: 'Crawfish Tail (Rice)',
        price: 8.79,
        group: 'Popcorn Shrimp',
        amount: 1,
    },
    // Chicken 
    {
        id: 30,
        title: '7pc Chicken Wing (Rice)',
        price: 7.29,
        group: 'Chicken',
        amount: 1,
    },
    {
        id: 31,
        title: '7pc Hot Wing',
        price: 8.29,
        group: 'Chicken',
        amount: 1,
    },
    {
        id: 32,
        title: '7pc BBQ Wing',
        price: 8.29,
        group: 'Chicken',
        amount: 1,
    },
    {
        id: 33,
        title: '5pc Chicken Strips',
        price: 6.79,
        group: 'Chicken',
        amount: 1,
    },
    {
        id: 34,
        title: '3 Sticks of Pineapple Chicken (Rice)',
        price: 10.29,
        group: 'Chicken',
        amount: 1,
    },
    // Po Boys
    {
        id: 35,
        title: 'Shrimp Po-boy',
        price: 8.69,
        group: 'Po-Boys',
        amount: 1,
    },
    {
        id: 36,
        title: 'Fish Po-boy',
        price: 8.69,
        group: 'Po-Boys',
        amount: 1,
    },
    {
        id: 37,
        title: 'Oyster Po-boy',
        price: 9.39,
        group: 'Po-Boys',
        amount: 1,
    },
    {
        id: 38,
        title: 'Crawfish Po-boy',
        price: 9.39,
        group: 'Po-Boys',
        amount: 1,
    },
    {
        id: 39,
        title: 'Chicken Po-boy',
        price: 8.29,
        group: 'Po-Boys',
        amount: 1,
    },
    {
        id: 40,
        title: 'Sausage Po-boy',
        price: 7.89,
        group: 'Po-Boys',
        amount: 1,
    },
    //Burgers
    {
        id: 41,
        title: 'Shrimp Burger',
        price: 5.79,
        group: 'Burgers',
        amount: 1,
    },
    {
        id: 42,
        title: 'Fish Burger',
        price: 5.79,
        group: 'Burgers',
        amount: 1,
    },
    {
        id: 43,
        title: 'Pork Chop Burger',
        price: 6.29,
        group: 'Burgers',
        amount: 1,
    },
    {
        id: 44,
        title: 'Chicken Burger',
        price: 5.79,
        group: 'Burgers',
        amount: 1,
    },
    //Pork Chop
    {
        id: 45,
        title: '1 Pork Chop',
        price: 6.19,
        group: 'Pork Chop',
        amount: 1,
    },
    {
        id: 46,
        title: '2 Pork Chop',
        price: 8.59,
        group: 'Pork Chop',
        amount: 1,
    },
    //Chinese Food
    {
        id: 47,
        title: 'Sweet & Sour Chicken',
        price: 10.29,
        group: 'Chinese Food',
        amount: 1,
    },
    {
        id: 48,
        title: 'Sesame Chicken',
        price: 10.29,
        group: 'Chinese Food',
        amount: 1,
    },
    {
        id: 49,
        title: 'Shrimp Noodle',
        price: 10.29,
        group: 'Chinese Food',
        amount: 1,
    },
    {
        id: 50,
        title: 'Small Noodle',
        price: 6.19,
        group: 'Chinese Food',
        amount: 1,
    },
    {
        id: 51,
        title: '1 Eggroll',
        price: 1.39,
        group: 'Chinese Food',
        amount: 1,
    },
    {
        id: 52,
        title: '3 Eggroll with Rice',
        price: 5.69,
        group: 'Chinese Food',
        amount: 1,
    },
    {
        id: 53,
        title: 'Small Rice',
        price: 4.59,
        group: 'Chinese Food',
        amount: 1,
    },
    {
        id: 54,
        title: 'Medium Rice',
        price: 6.69,
        group: 'Chinese Food',
        amount: 1,
    },
    {
        id: 55,
        title: 'Large Rice',
        price: 8.69,
        group: 'Chinese Food',
        amount: 1,
    },
    // Salad
    {
        id: 56,
        title: 'Small Salad',
        price: 3.69,
        group: 'Salad',
        amount: 1,
    },
    {
        id: 57,
        title: 'Large Salad',
        price: 5.89,
        group: 'Salad',
        amount: 1,
    },
    {
        id: 58,
        title: 'Shrimp Salad',
        price: 7.29,
        group: 'Salad',
        amount: 1,
    },
    {
        id: 59,
        title: 'Chicken Salad',
        price: 7.19,
        group: 'Salad',
        amount: 1,
    },
    // Gubmo
    {
        id: 60,
        title: 'Small Gumbo',
        price: 7.79,
        group: 'Gumbo',
        amount: 1,
    },
    {
        id: 61,
        title: 'Medium Gumbo',
        price: 8.99,
        group: 'Gumbo',
        amount: 1,
    },
    {
        id: 62,
        title: 'Large Gumbo',
        price: 10.49,
        group: 'Gumbo',
        amount: 1,
    },
    //Red Bean
    {
        id: 63,
        title: 'Small Red Bean',
        price: 6.89,
        group: 'Red Bean',
        amount: 1,
    },
    {
        id: 64,
        title: 'Medium Red Bean',
        price: 7.89,
        group: 'Red Bean',
        amount: 1,
    },
    {
        id: 65,
        title: 'Large Red Bean',
        price: 8.89,
        group: 'Red Bean',
        amount: 1,
    },
    //Party Tray
    {
        id: 66,
        title: '50 Fish Strips',
        price: 34.00,
        group: 'Party Tray',
        amount: 1,
    },
    {
        id: 67,
        title: '50pc Chicken Wings',
        price: 49.00,
        group: 'Party Tray',
        amount: 1,
    },
    {
        id: 68,
        title: '50pc Chicken Strips',
        price: 55.00,
        group: 'Party Tray',
        amount: 1,
    },
    {
        id: 69,
        title: 'Noodle Tray',
        price: 42.00,
        group: 'Party Tray',
        amount: 1,
    },
    {
        id: 70,
        title: 'Small Pan of Rice',
        price: 26.00,
        group: 'Party Tray',
        amount: 1,
    },
    {
        id: 71,
        title: 'Large Pan of Rice',
        price: 48.00,
        group: 'Party Tray',
        amount: 1,
    },
    //Add On
    {
        id: 72,
        title: '3 Shrimp',
        price: 3.35,
        group: 'Add On',
        amount: 1,
    },
    {
        id: 73,
        title: '1 Fish',
        price: 3.45,
        group: 'Add On',
        amount: 1,
    },
    {
        id: 74,
        title: '3 Oyster',
        price: 4.07,
        group: 'Add On',
        amount: 1,
    },
    {
        id: 75,
        title: '1 Piece Pork Chop',
        price: 5.35,
        group: 'Add On',
        amount: 1,
    },
    {
        id: 76,
        title: '1 Stick of Pineapple Chicken',
        price: 3.50,
        group: 'Add On',
        amount: 1,
    },
    {
        id: 77,
        title: 'Small French Fries',
        price: 3.09,
        group: 'Add On',
        amount: 1,
    },
    {
        id: 78,
        title: 'Large French Fries',
        price: 5.67,
        group: 'Add On',
        amount: 1,
    },
    {
        id: 79,
        title: '4pc Chicken Wing',
        price: 4.02,
        group: 'Add On',
        amount: 1,
    },
    {
        id: 80,
        title: '4pc Hot Wing',
        price: 4.12,
        group: 'Add On',
        amount: 1,
    },
    {
        id: 81,
        title: '4pc BBQ Wing',
        price: 4.12,
        group: 'Add On',
        amount: 1,
    },
    {
        id: 82,
        title: '2 Eggrolls & Rice',
        price: 4.69,
        group: 'Chinese Food',
        amount: 1,
    },
    {
        id: 83,
        title: 'Change Fries for Rice',
        price: 1.29,
        group: 'Add On',
        amount: 1
    }
]

export default products;